# Generated by Django 6.0 on 2025-12-05 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OquvMarkaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markaz_nomi', models.CharField(max_length=200)),
                ('kurs_nomi', models.CharField(max_length=200)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('malumot', models.TextField()),
                ('rasm', models.ImageField(blank=True, null=True, upload_to='markazlar/')),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.yonalish')),
            ],
        ),
    ]
